language: java

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.3
  allow_failures:
    - os: osx
  
cache:
  directories:
  - $HOME/.m2
  
jdk:
  - oraclejdk10
  - oraclejdk-ea
  - openjdk10
  - openjdk11
script: 
- cd ./OSS_TodoList/
- ant build
