language: java

dist: trusty

matrix:

  include:
    - os: linux
    - os: osx
      osx_image: xcode9.3
    
  allow_failures:
    - os: osx
  
cache:
  directories:
  - $HOME/.m2
  
jdk:
  - oraclejdk8
  - oraclejdk10
  - oraclejdk-ea
  - openjdk10
  - openjdk11
  
script: 
  - cd ./OSS_TodoList/
  - ant build
  - cd ../
  - java -jar todo-b7.jar --version
  - java -jar todo-b7.jat --a
