language: java

matrix:

  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.3
      script: 
        - source /opt/jdk_switcher/jdk_switcher.sh
      
  allow_failures:
    - os: osx
  
cache:
  directories:
  - $HOME/.m2
  
jdk:
  - oraclejdk8
  - oraclejdk10
  - oraclejdk-ea
  - openjdk10
  - openjdk11
  
script: 
- cd ./OSS_TodoList/
- ant build
